import Link from 'next/link';
import { RiArrowRightLine, RiCheckboxCircleLine, RiFlowChart, RiMicLine, RiFileTextLine, RiShieldCheckLine, RiSparklingLine } from 'react-icons/ri';
import LandingVoiceWidget from '@/components/LandingVoiceWidget';

const steps = [
  { number: '01', icon: RiFlowChart, title: 'Design the flow', copy: 'Map questions, guidance, and handoffs in a visual workflow built for real conversations.' },
  { number: '02', icon: RiMicLine, title: 'Let voice lead', copy: 'Your voice agent asks, listens, clarifies, and fills the form as answers arrive.' },
  { number: '03', icon: RiFileTextLine, title: 'Collect clear answers', copy: 'Participants review their answers and submit a record you can find in your workspace.' },
];

export default function RootPage() {
  return <div className="min-h-screen bg-[#fefcff] text-[#1c1233]">
    <header className="sticky top-0 z-30 border-b border-violet-100/70 bg-white/90 backdrop-blur-xl">
      <nav aria-label="Main navigation" className="mx-auto flex h-20 max-w-[1440px] items-center justify-between gap-5 px-5 sm:px-8 lg:px-12">
        <Link href="/" className="flex items-center gap-3" aria-label="Kavqen home"><span className="flex h-10 w-10 items-center justify-center rounded-[14px] bg-gradient-to-br from-violet-700 via-indigo-600 to-cyan-500 text-xl font-black text-white shadow-lg shadow-violet-300">K</span><span className="text-xl font-bold tracking-tight">Kavqen<span className="text-violet-600">.</span></span></Link>
        <div className="hidden items-center gap-8 text-sm font-semibold text-slate-600 md:flex"><a href="#platform" className="hover:text-violet-700">Platform</a><a href="#how-it-works" className="hover:text-violet-700">How it works</a><a href="#use-cases" className="hover:text-violet-700">Use cases</a></div>
        <div className="flex items-center gap-2 sm:gap-3"><Link href="/login" className="rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-700 hover:bg-violet-50 sm:px-4">Sign in</Link><Link href="/signup" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#251044] px-4 text-sm font-semibold text-white transition hover:bg-violet-800 sm:px-5">Get started<RiArrowRightLine aria-hidden="true" /></Link></div>
      </nav>
    </header>

    <main>
      <section className="relative mx-3 mt-3 overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_78%_25%,#c7aaff_0%,#e4d4ff_30%,#f7eefd_66%,#eee2ff_100%)] px-5 py-20 sm:mx-5 sm:px-10 lg:px-14 lg:py-28" aria-labelledby="hero-title">
        <div className="pointer-events-none absolute -left-20 bottom-0 h-60 w-60 rounded-full bg-violet-400/20 blur-[90px]" /><div className="pointer-events-none absolute -right-24 -top-20 h-80 w-80 rounded-full bg-white/40 blur-[80px]" />
        <div className="relative mx-auto grid max-w-[1320px] items-center gap-14 lg:grid-cols-[1.06fr_.94fr]">
          <div><span className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white/70 px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-violet-700"><RiSparklingLine aria-hidden="true" /> Voice AI for better conversations</span>
            <h1 id="hero-title" className="mt-7 max-w-3xl text-[clamp(3.2rem,6.2vw,6.8rem)] font-semibold leading-[1.03] tracking-[-0.065em] text-[#1c1233]">Every form starts with <span className="text-violet-700">a conversation.</span></h1>
            <p className="mt-7 max-w-xl text-lg leading-relaxed text-slate-700 sm:text-xl">Build voice agents that listen, guide, and turn spoken answers into structured submissions. Give every participant a simpler way to complete your workflow.</p>
            <div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/signup" className="inline-flex h-12 items-center gap-2 rounded-xl bg-[#251044] px-6 text-sm font-semibold text-white shadow-lg shadow-violet-800/10 transition hover:-translate-y-0.5 hover:bg-violet-800">Start building<RiArrowRightLine aria-hidden="true" /></Link><a href="#how-it-works" className="inline-flex h-12 items-center rounded-xl border border-violet-200 bg-white/70 px-6 text-sm font-semibold text-[#251044] transition hover:bg-white">Explore the platform</a></div>
            <div className="mt-10 flex flex-wrap gap-x-6 gap-y-2 text-xs font-semibold text-slate-600"><span className="flex items-center gap-2"><RiCheckboxCircleLine className="text-violet-700" />Visual workflows</span><span className="flex items-center gap-2"><RiCheckboxCircleLine className="text-violet-700" />Live voice guidance</span><span className="flex items-center gap-2"><RiCheckboxCircleLine className="text-violet-700" />Reviewable submissions</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-[520px] lg:translate-x-3">
            <div className="absolute -inset-3 rotate-2 rounded-[2rem] border border-white/70 bg-white/20 shadow-[0_35px_80px_rgba(88,46,160,.15)] sm:-inset-5" />
            <div className="relative overflow-hidden rounded-[1.75rem] border border-white/90 bg-white shadow-[0_30px_75px_rgba(72,45,126,.18)]">
              <div className="flex items-center justify-between gap-3 border-b border-slate-100 px-5 py-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-violet-700 to-cyan-500 text-lg font-black text-white">K</span><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-900">Kavqen voice agent</p><p className="text-xs text-slate-500">Intake form · Preview</p></div></div><span className="flex shrink-0 items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />Live</span></div>
              <div className="p-5 sm:p-6">
                <div className="rounded-2xl bg-[#f7f4ff] p-4 sm:p-5"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.16em] text-violet-600"><RiSparklingLine aria-hidden="true" /> Agent speaking</div><p className="mt-3 text-base font-medium leading-relaxed text-slate-800 sm:text-lg">“Hi! What name should I use for your form?”</p></div>
                <div className="mt-4 flex items-center gap-3 rounded-2xl border border-violet-100 bg-white p-3.5 shadow-sm"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-cyan-500 to-violet-700 text-white"><RiMicLine aria-hidden="true" /></span><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-slate-800">Participant response</p><p className="truncate text-sm text-slate-500">“You can call me Alex.”</p></div><div aria-hidden="true" className="flex h-7 items-center gap-[3px]">{[8,15,24,13,20,10,17,7].map((height, index) => <span key={index} className="w-[3px] rounded-full bg-violet-500" style={{ height }} />)}</div></div>
                <div className="mt-5 border-t border-slate-100 pt-4"><div className="flex items-center justify-between"><p className="text-[11px] font-bold uppercase tracking-[0.15em] text-slate-400">Form updated</p><RiCheckboxCircleLine className="text-emerald-500" aria-hidden="true" /></div><div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><p className="text-[11px] font-medium text-slate-500">Full name</p><p className="mt-1 text-sm font-semibold text-slate-900">Alex</p></div></div>
              </div>
            </div>
            <div className="absolute -bottom-5 -left-3 hidden -rotate-3 rounded-xl border border-white bg-white px-4 py-2.5 text-xs font-semibold text-violet-800 shadow-lg sm:block">Voice in. Answers ready.</div>
          </div>
        </div>
        <div aria-hidden="true" className="pointer-events-none absolute inset-x-0 bottom-0 h-8 opacity-40 [background-image:radial-gradient(#8855dd_1px,transparent_1px)] [background-size:7px_7px]" />
      </section>

      <section id="platform" className="mx-auto max-w-[1320px] scroll-mt-24 px-5 py-24 sm:px-8 lg:py-32"><div className="grid gap-10 lg:grid-cols-2 lg:gap-20"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Built around human conversations</p><h2 className="mt-5 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">From a spoken moment to a complete response.</h2></div><p className="self-end text-lg leading-relaxed text-slate-600">Kavqen brings your workflow, voice agent, and form together. Participants can speak naturally, review what was captured, and submit with confidence. Owners see the responses in one place.</p></div>
        <div className="mt-14 grid gap-5 md:grid-cols-3">{steps.map(step => <article key={step.number} className="rounded-[1.6rem] border border-violet-100 bg-white p-7 shadow-[0_15px_45px_rgba(78,38,137,.05)]"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-50 text-violet-700"><step.icon className="h-6 w-6" aria-hidden="true" /></span><p className="mt-9 text-xs font-bold tracking-widest text-violet-500">{step.number} / 03</p><h3 className="mt-3 text-xl font-semibold">{step.title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{step.copy}</p></article>)}</div>
      </section>

      <section id="how-it-works" className="scroll-mt-24 bg-[#211039] px-5 py-24 text-white sm:px-8 lg:py-32"><div className="mx-auto grid max-w-[1320px] items-center gap-14 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-300">Your workflow, brought to life</p><h2 className="mt-5 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">Design once. Guide every conversation.</h2><p className="mt-6 max-w-xl text-lg leading-relaxed text-violet-100/75">Create a workflow, publish a form, and share access with participants. The voice agent walks through each answer while the form updates beside it.</p><Link href="/signup" className="mt-8 inline-flex h-12 items-center gap-2 rounded-xl bg-white px-5 text-sm font-semibold text-[#251044] hover:bg-violet-100">Explore the studio<RiArrowRightLine aria-hidden="true" /></Link></div><div className="rounded-[2rem] border border-white/15 bg-white/5 p-5 shadow-2xl backdrop-blur sm:p-8"><div className="flex items-center justify-between border-b border-white/10 pb-5"><p className="font-semibold">Intake workflow</p><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-300">Published</span></div><div className="mt-7 space-y-3">{['Welcome and introduce the form','Ask one question at a time','Confirm important details','Review and submit answers'].map((item, index) => <div key={item} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-violet-400/20 text-xs font-bold text-violet-200">0{index + 1}</span><span className="text-sm text-violet-50">{item}</span>{index < 3 && <RiArrowRightLine className="ml-auto text-violet-400" aria-hidden="true" />}</div>)}</div></div></div></section>

      <section id="use-cases" className="mx-auto max-w-[1320px] scroll-mt-24 px-5 py-24 sm:px-8 lg:py-32"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-600">Made for the details</p><h2 className="mt-5 text-4xl font-semibold tracking-tight sm:text-5xl">More clarity at every step.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3"><div className="rounded-[1.6rem] bg-[#f1e8ff] p-8"><RiMicLine className="h-8 w-8 text-violet-700" aria-hidden="true" /><h3 className="mt-8 text-xl font-semibold">Conversational intake</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">Make long forms feel like a guided exchange.</p></div><div className="rounded-[1.6rem] bg-[#e8f4ff] p-8"><RiFileTextLine className="h-8 w-8 text-sky-700" aria-hidden="true" /><h3 className="mt-8 text-xl font-semibold">Structured submissions</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">Keep submitted answers organized and easy to review.</p></div><div className="rounded-[1.6rem] bg-[#eeeaf8] p-8"><RiShieldCheckLine className="h-8 w-8 text-indigo-700" aria-hidden="true" /><h3 className="mt-8 text-xl font-semibold">Controlled access</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">Share forms with an invitation or a time limited access code.</p></div></div></section>

      <section className="mx-3 mb-4 rounded-[2rem] bg-[linear-gradient(115deg,#d7c5ff,#f3eaff_60%,#dbebff)] px-6 py-20 text-center sm:mx-5 sm:px-10 lg:py-28"><p className="text-xs font-bold uppercase tracking-[0.2em] text-violet-700">Start a better conversation</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-semibold leading-tight tracking-tight sm:text-6xl">Give every answer room to be heard.</h2><p className="mx-auto mt-6 max-w-xl text-lg text-slate-700">Build your first voice workflow in Kavqen.</p><Link href="/signup" className="mt-8 inline-flex h-12 items-center gap-2 rounded-xl bg-[#251044] px-6 text-sm font-semibold text-white hover:bg-violet-800">Get started<RiArrowRightLine aria-hidden="true" /></Link></section>
    </main>
    <footer className="mx-auto flex max-w-[1320px] flex-col gap-5 px-5 py-10 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-8"><span className="font-semibold text-[#251044]">Kavqen.</span><span>Voice agents for guided form conversations.</span><div className="flex gap-5"><Link href="/login" className="hover:text-violet-700">Sign in</Link><Link href="/signup" className="hover:text-violet-700">Get started</Link></div></footer>
    <LandingVoiceWidget />
  </div>;
}
